echo "export ROOT_HELPER_FUNCS_PATH=$PWD" >> ~/.bash_profile
export ROOT_HELPER_FUNCS_PATH=$PWD
echo "export PYTHON_PATH=$ROOT_HELPER_FUNCS_PATH:$PYTHON_PATH" >> ~/.bash_profile
export PYTHON_PATH=$ROOT_HELPER_FUNCS_PATH:$PYTHON_PATH
